use std::path::PathBuf;

use lazy_static::lazy_static;

// root directory from perspective of pico8 process
pub const DRIVE_DIR: &str = "drive";

lazy_static! {
    pub static ref EXE_DIR: PathBuf = PathBuf::from("drive/exe");
    pub static ref CART_DIR: PathBuf = PathBuf::from("drive/carts");
    pub static ref GAMES_DIR: PathBuf = PathBuf::from("drive/carts/games");
    pub static ref MUSIC_DIR: PathBuf = PathBuf::from("drive/carts/music");
    pub static ref LABEL_DIR: PathBuf = PathBuf::from("drive/carts/labels");
    pub static ref BBS_CART_DIR: PathBuf = PathBuf::from("drive/bbs/carts");
}

// path of png files generated by pico8
pub const RAW_SCREENSHOT_PATH: &str = "drive/screenshots";

// path of scaled cart screenshots
pub const SCREENSHOT_PATH: &str = "drive/carts/screenshots";
